[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "file-tag-parser"
version = "0.1"
dependencies = [
    "pandas>=2.0",
    "parse>=1.2.0",
    "parse-type>=0.6.4"
]